#
# MKDOCS CONFIGURATION FILE
# see: https://www.mkdocs.org/user-guide/configuration/
#

site_name: Smart Control Project Documentation
site_description: "Smart Buildings"
site_dir: docs_site # NOTE: should not be within the docs dir
site_url: https://google.github.io/sbsim/
repo_url: https://github.com/google/sbsim
repo_name: google/sbsim
#repo_icon: fontawesome/brands/github

#
# THEME
# default: (readthedocs / mkdocs), third-party: material
#

theme:
  name: material
  features:
    #- navigation.tabs # puts tabs under top navbar
    - navigation.sections # splits left sidebar into sections


#
# NAVIGATION
#

nav:
  - 'Home': index.md
  - 'Setup': setup.md
  - 'Contributing': contributing.md
  - 'Documentation Site': docs-site.md
  - 'API Reference':
    - api/config.md
    - api/dataset.md
    - api/environment.md
    - api/models.md
    - api/reinforcement_learning.md
    - api/reward.md
    - api/simulator.md


#
# API DOCS
#

markdown_extensions:
  - toc:
      # adds clickable link anchors for all headings:
      permalink: "#" # true, "#", "¶", "⚓︎", etc

plugins:
  - search

  # https://mkdocstrings.github.io/python/usage/
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths:
            - .  # look in the current directory for the "smart_control" dir
          options:
            docstring_style: google
            docstring_section_style: "table" # "table", "list", "spacy"
            show_source: false
            show_signature_annotations: true # type hints
            show_root_heading: true # HTML heading for the import path
            show_root_full_path: true # show full module import path
            show_root_members_full_path: false
            show_root_toc_entry: true
            members_order: alphabetical # "alphabetical", "source", "__all__"
            filters: ["!^_"] # exclude private / protected members
            inherited_members: true
            show_inheritance_diagram: true # paid feature?
            line_length: 80
            show_category_heading: false # "Classes", "Functions" etc.
            show_symbol_type_heading: true # "Class", "Function", etc
            show_symbol_type_toc: true # "mod", "class", "meth", etc.
            merge_init_into_class: true
            show_if_no_docstring: false
            separate_signature: true
            annotations_path: "brief" # "brief", "source", or "full"
