#
# MKDOCS CONFIGURATION FILE
# see: https://www.mkdocs.org/user-guide/configuration/
#

site_name: Smart Control Project Documentation
site_description: "Smart Buildings"
site_dir: docs_site # NOTE: should not be within the docs dir
site_url: https://google.github.io/sbsim/
repo_url: https://github.com/google/sbsim
repo_name: google/sbsim
#repo_icon: fontawesome/brands/github

#
# THEME
# default: (readthedocs / mkdocs), third-party: material
#
theme:
  name: material
  features:
    #- navigation.tabs # puts tabs under top navbar
    - navigation.sections # splits left sidebar into sections


#
# NAVIGATION
#
nav:
  - Home: index.md
  - 'Setup': setup.md
  - 'Contributing': contributing.md
  - 'API Reference':
    - api/dataset.md
    - api/environment.md
    - api/models.md
    - api/reinforcement_learning.md
    - api/reward.md
    - api/simulator.md

  #- 'Documentation': README.md

#
# API DOCS
#

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      # You can configure options for the Python handler specifically here
      handlers:
        python:
          # Paths where mkdocstrings should look for your Python code.
          # Since your 'my_project' library is next to mkdocs.yml,
          # you'd likely just need to include its root directory.
          paths:
            - .  # This tells mkdocstrings to look in the current directory (your project root)

          # Options for how docstrings are parsed and rendered
          options:
            docstring_style: google
            show_source: true       # Show the source code of documented objects
            show_signature_annotations: true # Show type hints in signatures
            show_root_heading: true # Show a top-level heading for modules/classes
            show_root_full_path: true
            members_order: alphabetical # Or "source", "__all__"
            filters: ["!^_"] # Exclude private members (starting with _) by default
            # You can add more specific filters, e.g., to exclude all private/protected
            # but keep __init__ methods: filters: ["!^_", "^__init__$"]
