"""Utilities for reinforcement learning agents, particularly for data collection.

This module provides helper functions for creating scripted policies that can be
used during the data collection phase of RL agent training. Scripted policies
define a sequence of actions to be taken by the agent, independent of the
environment's state, which can be useful for initial exploration or for
generating specific types of experiences.
"""

from typing import List, Sequence, Tuple # Changed from typing.Sequence to List for Policy type hint

import numpy as np
import tensorflow as tf

# Type Aliases
PolicyStep = Tuple[int, tf.Tensor]
"""Represents a single step in a scripted policy.

A `PolicyStep` is a tuple where:
  - The first element (int) is the number of environment time steps for which
    the action should be held constant.
  - The second element (tf.Tensor) is the action tensor to be applied.
"""

Policy = List[PolicyStep] # Changed from Sequence to List for concrete type
"""Represents a scripted policy as a list of `PolicyStep` tuples.

This sequence defines the actions an agent will take over a series of steps.
"""


def create_random_walk_collect_script(
    initial_policy_values: tf.Tensor,
    time_steps_per_step: int,
    num_policy_steps: int,
    step_magnitude: float,
    upper_bound: float = 1.0,
    lower_bound: float = -1.0,
) -> Policy:
  """Generates a scripted random walk policy for data collection.

  This function creates a policy where actions are determined by a random walk
  process. Starting from `initial_policy_values`, each subsequent action in the
  script is generated by adding a random perturbation (of size `step_magnitude`)
  to the previous action, independently for each dimension of the action space.
  The resulting actions are clipped to stay within `[lower_bound, upper_bound]`.
  Each action in the random walk is held constant for `time_steps_per_step`
  environment steps.

  This type of policy is useful for encouraging exploration during the initial
  phases of RL training or for populating a replay buffer with diverse
  experiences.

  Args:
    initial_policy_values (tf.Tensor): A 1D TensorFlow tensor representing the
      starting action values for the random walk. Its shape determines the
      dimensionality of the action space.
    time_steps_per_step (int): The number of environment time steps each
      action in the generated policy script will be held constant.
    num_policy_steps (int): The total number of distinct random walk policy
      steps (action changes) to generate in the script.
    step_magnitude (float): The fixed magnitude of the random perturbation
      applied at each step of the random walk (can be positive or negative).
    upper_bound (float): The upper limit for clipping the action values.
    lower_bound (float): The lower limit for clipping the action values.

  Returns:
    Policy: A list of `PolicyStep` tuples representing the generated random
    walk policy. Each tuple is `(duration, action_tensor)`.

  Raises:
    ValueError: If input parameters are invalid (e.g., empty
      `initial_policy_values`, `upper_bound` <= `lower_bound`, non-positive
      `step_magnitude`, `step_magnitude` too large relative to bounds,
      or non-positive `time_steps_per_step`).
  """
  if not isinstance(initial_policy_values, tf.Tensor) or \
     initial_policy_values.ndim == 0 or \
     initial_policy_values.shape[0] < 1:
    raise ValueError(
        "initial_policy_values must be a 1D tf.Tensor with at least one element."
    )
  action_dimensionality = initial_policy_values.shape[0]

  if upper_bound <= lower_bound:
    raise ValueError("upper_bound must be strictly greater than lower_bound.")

  if tf.reduce_any(initial_policy_values > upper_bound) or \
     tf.reduce_any(initial_policy_values < lower_bound):
    raise ValueError(
        "All elements of initial_policy_values must be within "
        "[lower_bound, upper_bound]."
    )

  if step_magnitude <= 0.0:
    raise ValueError("step_magnitude must be positive.")

  action_range = upper_bound - lower_bound
  if action_range > 0 and step_magnitude > 0.25 * action_range:
    # This check helps prevent steps that are too large relative to the action space.
    raise ValueError(
        "step_magnitude should not exceed 25% of the range between "
        "upper_bound and lower_bound."
    )

  if time_steps_per_step < 1:
    raise ValueError("time_steps_per_step must be an integer >= 1.")

  # Define constant tensors for clipping bounds
  clip_upper_bound = tf.constant([upper_bound] * action_dimensionality, dtype=tf.float32)
  clip_lower_bound = tf.constant([lower_bound] * action_dimensionality, dtype=tf.float32)

  # Initialize the policy script with the starting action
  random_walk_policy_script: Policy = [
      (time_steps_per_step, initial_policy_values)
  ]
  current_action_values = initial_policy_values

  # Generate subsequent policy steps
  while len(random_walk_policy_script) < num_policy_steps:
    # Generate a random step direction (-1 or 1) for each action dimension
    random_directions = tf.constant(
        np.random.choice([-1.0, 1.0], size=action_dimensionality),
        dtype=tf.float32
    )
    random_perturbation = random_directions * step_magnitude

    next_action_values_unclipped = tf.add(current_action_values, random_perturbation)
    next_action_values_clipped = tf.clip_by_value(
        next_action_values_unclipped,
        clip_value_min=clip_lower_bound,
        clip_value_max=clip_upper_bound
    )
    random_walk_policy_script.append(
        (time_steps_per_step, next_action_values_clipped)
    )
    current_action_values = next_action_values_clipped

  return random_walk_policy_script
