"""Defines the base interface for reinforcement learning observers.

This module provides an abstract base class (ABC), `Observer`, which outlines
the essential methods that all concrete observer implementations should provide.
Observers are components designed to monitor an RL agent's interaction with an
environment by processing the trajectories generated during training or evaluation.
"""

import abc

from tf_agents.trajectories import trajectory as trajectory_lib


class Observer(abc.ABC):
  """Abstract base class for observers in reinforcement learning.

  Observers are callable objects that process trajectories generated by an
  agent interacting with an environment. They can be used for a variety of
  purposes, such as:
  - Collecting and aggregating metrics (e.g., average reward, episode length).
  - Logging data to files or consoles.
  - Visualizing agent behavior or environment states.
  - Triggering specific actions based on observed events.

  Subclasses must implement the `__call__` and `reset` methods.
  """

  @abc.abstractmethod
  def __call__(self, trajectory: trajectory_lib.Trajectory) -> None:
    """Processes a single trajectory step from the agent-environment interaction.

    This method is invoked for each step (transition) that the agent takes.
    The `trajectory` object typically contains information like the observation,
    action taken, reward received, next observation, and episode boundary flags.

    Args:
      trajectory: A `tf_agents.trajectories.trajectory.Trajectory` object
        representing a single step or a batch of steps.
    """
    pass

  @abc.abstractmethod
  def reset(self) -> None:
    """Resets the observer's internal state.

    This method is typically called at the beginning of a new episode or
    evaluation run. It allows the observer to clear any accumulated data or
    state from the previous episode, ensuring that metrics or logs are handled
    correctly for the new episode.
    """
    pass
