"""Abstract base class for observers in reinforcement learning.

This module defines the `Observer` abstract base class (ABC), which serves as
an interface for all observers used in the reinforcement learning (RL)
framework. Observers are designed to monitor various aspects of the RL process,
such as agent behavior, environment interactions, and training progress.
"""

import abc

from tf_agents.trajectories import trajectory as trajectory_lib


class Observer(abc.ABC):
  """Abstract interface for observers that process agent trajectories.

  Observers are callable objects that are invoked with each trajectory segment
  generated by the agent interacting with the environment. They can be used for
  various purposes, including:
  - Logging metrics (e.g., rewards, episode lengths).
  - Storing data (e.g., for later analysis or visualization).
  - Triggering events based on specific conditions.
  - Visualizing agent behavior or environment state.

  Implementing classes must define the `__call__` method to process incoming
  trajectories and the `reset` method to clear any internal state at the
  beginning of new episodes or data collection periods.
  """

  @abc.abstractmethod
  def __call__(self, trajectory: trajectory_lib.Trajectory) -> None:
    """Processes a single trajectory step from the agent-environment interaction.

    This method is called by the data collection loop for each trajectory
    generated. Implementations should define what to do with this trajectory
    data (e.g., log it, store it, update internal metrics).

    Args:
      trajectory (trajectory_lib.Trajectory): A trajectory object representing
        a single step or a sequence of steps, containing information such as
        observation, action, reward, next_step_type, etc.
    """
    pass

  @abc.abstractmethod
  def reset(self) -> None:
    """Resets the observer's internal state.

    This method is typically called at the beginning of each new episode or
    before starting a new data collection phase. It allows the observer to
    clear any accumulated data or reset metrics specific to a single episode
    or run.
    """
    pass
