"""Executable scripts for reinforcement learning tasks.

This package contains Python scripts that are intended to be run directly from
the command line to perform various tasks related to the reinforcement learning
setup for smart building control. These tasks include training RL agents,
populating replay buffers with initial data, and potentially evaluating
trained policies.

Modules:
  populate_starter_buffer: A script to fill the replay buffer with experiences
    generated by a predefined policy (e.g., a schedule-based policy) before
    starting agent training.
  train: The main script for training a reinforcement learning agent (e.g., SAC)
    on the smart building environment. It typically handles environment setup,
    agent creation, training loop execution, and metric logging.
"""
